### ISSUE TITLE
More graceful handling of nix subprocesses dieing

### ISSUE THREAD

**Issue by jonringer** [Mic92/nixpkgs-review#146]
If a nix subprocess dies (I usually get it if the process gets OOM-killed while doing `nix-env -qaP`), you get a pretty odd error:
```
$ nix-env -f /home/jon/.cache/nixpkgs-review/pr-104686/nixpkgs -qaP --xml --out-path --show-trace --meta
$ git worktree prune
Traceback (most recent call last):
  File "/nix/store/013cl6waiqnjm1z2fhq43d36s2mnx9n0-nixpkgs-review-2.4.2/bin/.nix-review-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/013cl6waiqnjm1z2fhq43d36s2mnx9n0-nixpkgs-review-2.4.2/lib/python3.8/site-packages/nixpkgs_review/__init__.py", line 10, in main
    cli.main(command, args)
  File "/nix/store/013cl6waiqnjm1z2fhq43d36s2mnx9n0-nixpkgs-review-2.4.2/lib/python3.8/site-packages/nixpkgs_review/cli/__init__.py", line 228, in main
    args.func(args)
  File "/nix/store/013cl6waiqnjm1z2fhq43d36s2mnx9n0-nixpkgs-review-2.4.2/lib/python3.8/site-packages/nixpkgs_review/cli/pr.py", line 60, in pr_command
    contexts.append((pr, review.build_pr(pr)))
  File "/nix/store/013cl6waiqnjm1z2fhq43d36s2mnx9n0-nixpkgs-review-2.4.2/lib/python3.8/site-packages/nixpkgs_review/review.py", line 185, in build_pr
    return self.build_commit(base_rev, pr_rev)
  File "/nix/store/013cl6waiqnjm1z2fhq43d36s2mnx9n0-nixpkgs-review-2.4.2/lib/python3.8/site-packages/nixpkgs_review/review.py", line 139, in build_commit
    merged_packages = list_packages(str(self.worktree_dir()), check_meta=True)
  File "/nix/store/013cl6waiqnjm1z2fhq43d36s2mnx9n0-nixpkgs-review-2.4.2/lib/python3.8/site-packages/nixpkgs_review/review.py", line 287, in list_packages
    return parse_packages_xml(nix_env.stdout)
  File "/nix/store/013cl6waiqnjm1z2fhq43d36s2mnx9n0-nixpkgs-review-2.4.2/lib/python3.8/site-packages/nixpkgs_review/review.py", line 228, in parse_packages_xml
    for (event, elem) in context:
  File "/nix/store/cqh3nsk4z8lc960g8yqvz5nf2f6qx9v0-python3-3.8.6/lib/python3.8/xml/etree/ElementTree.py", line 1233, in iterator
    root = pullparser._close_and_return_root()
  File "/nix/store/cqh3nsk4z8lc960g8yqvz5nf2f6qx9v0-python3-3.8.6/lib/python3.8/xml/etree/ElementTree.py", line 1280, in _close_and_return_root
    root = self._parser.close()
xml.etree.ElementTree.ParseError: no element found: line 1404677, column 0
```
It might be nice to wrap this in a try.. catch and inspect if the underlying command was killed.

**Comment by Mic92** [comment]
Agreed.

**Comment by Mic92** [comment]
I maybe should also start splitting off nixpkgs into smaller packages

**Comment by eliasp** [comment]
Seeing the same happening here on a bit older DELL XPS 13 L322X with 8G/2G of RAM/swap, running `nixpkgs-review pr 104810`.

**Comment by Mic92** [comment]
I also see this with zfs and 16GB on my laptop.

**Comment by Mic92** [comment]
Should be fixed in https://github.com/Mic92/nixpkgs-review/commit/e8c17ba145c1abfb1ea32f5db4474d0cccf25666
