### ISSUE TITLE
AttributeError: module 'enum' has no attribute 'IntFlag'

### ISSUE THREAD

**Issue by SuperSandro2000** [Mic92/nixpkgs-review#148]
```
nixpkgs-review pr 105141                                                                                                                                             $ git -c fetch.prune=false fetch --force https://github.com/NixOS/nixpkgs master:refs/nixpkgs-review/0 pull/105141/head:refs/nixpkgs-review/1
remote: Enumerating remote: Enumerating objects: 26, done.
remote: Counting objects: 100% (22/22), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 12 (delta 9), reused 8 (delta 6), pack-reused 0
Unpacking objects: 100% (12/12), 1.44 KiB | 58.00 KiB/s, done.
From https://github.com/NixOS/nixpkgs
   ec421ca248c4..ab3de811930f  master                -> refs/nixpkgs-review/0
 + d73a3ecdac58...ac3f60095b51 refs/pull/105141/head -> refs/nixpkgs-review/1  (forced update)
Auto packing the repository in background for optimum performance.
See "git help gc" for manual housekeeping.
$ git worktree add /Users/user/.cache/nixpkgs-review/pr-105141/nixpkgs ab3de811930f3aad758da76b29ffb4482571f256
Preparing worktree (detached HEAD ab3de811930f)
Updating files: 100% (23333/23333), done.
HEAD is now at ab3de811930f Merge pull request #105158 from r-ryantm/auto-update/evolution
$ git merge --no-commit ac3f60095b51ab78b35aa445f2667d28d27b8650
Already up to date.
$ nix --experimental-features nix-command build --no-link --keep-going --option build-use-sandbox relaxed -f /Users/user/.cache/nixpkgs-review/pr-105141/build.nix

Link to currently reviewing PR:
https://github.com/NixOS/nixpkgs/pull/105141

2 packages built:
python27Packages.browsermob-proxy python27Packages.marionette-harness

$ nix-shell /Users/user/.cache/nixpkgs-review/pr-105141/shell.nix
Lookup quick command  examples with tldr.

[nix-shell:~/.cache/nixpkgs-review/pr-105141]$ nixpkgs-review post-result
Traceback (most recent call last):
  File "/nix/store/vn4v02vzwq8bslsy4ifch686napfsa0j-nixpkgs-review-2.5.0/bin/.nixpkgs-review-wrapped", line 4, in <module>
    import re
  File "/nix/store/0mabx9absir73mmijrsv0dsyvyya463r-python3-3.8.6/lib/python3.8/re.py", line 145, in <module>
    class RegexFlag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'
```

**Comment by Mic92** [comment]
Looks like `PYTHONPATH` is polluted in your nix-shell due to python2.

**Comment by Mic92** [comment]
nixpkgs would need the same `--unset` in its wrapper.
