### ISSUE TITLE
"CalledProcessError: [...] returned non-zero exit status" when exiting nixpkgs-review shell

### ISSUE THREAD

**Issue by pacien** [Mic92/nixpkgs-review#152]
The problem can be reproduced by running the same sequence of commands as below.

```
❯ nixpkgs-review pr 106645
$ git -c fetch.prune=false fetch --force https://github.com/NixOS/nixpkgs master:refs/nixpkgs-review/0 pull/106645/head:refs/nixpkgs-review/1
$ git worktree add /home/kea/.cache/nixpkgs-review/pr-106645-6/nixpkgs 10fafe2125bab693fcbccd8f0cd480cee219b040
Preparing worktree (detached HEAD 10fafe2125b)
Updating files: 100% (23500/23500), done.
HEAD is now at 10fafe2125b Merge pull request #106596 from r-ryantm/auto-update/monero-gui
$ git merge --no-commit ca389ed6fbf14799b6d149ab8ef5f9118715f086
Automatic merge went well; stopped before committing as requested
$ nix build --no-link --keep-going --option build-use-sandbox relaxed -f /home/kea/.cache/nixpkgs-review/pr-106645-6/build.nix
https://github.com/NixOS/nixpkgs/pull/106645
1 package built:
beamerpresenter

$ nix-shell /home/kea/.cache/nixpkgs-review/pr-106645-6/shell.nix

[nix-shell:~/.cache/nixpkgs-review/pr-106645-6]$ ./results/beamerpresenter/bin/beamerpresenter /dev/null
     0.012 WARNING - qUncompress: Input data is corrupted
     0.012 CRITICAL - No presentation PDF file found.

[nix-shell:~/.cache/nixpkgs-review/pr-106645-6]$ exit
exit
$ git worktree prune
Traceback (most recent call last):
  File "/nix/store/9j1c708lhx3qj0l6fxanwjqjgsk8wrn4-nixpkgs-review-2.4.2/bin/.nixpkgs-review-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/9j1c708lhx3qj0l6fxanwjqjgsk8wrn4-nixpkgs-review-2.4.2/lib/python3.8/site-packages/nixpkgs_review/__init__.py", line 10, in main
    cli.main(command, args)
  File "/nix/store/9j1c708lhx3qj0l6fxanwjqjgsk8wrn4-nixpkgs-review-2.4.2/lib/python3.8/site-packages/nixpkgs_review/cli/__init__.py", line 228, in main
    args.func(args)
  File "/nix/store/9j1c708lhx3qj0l6fxanwjqjgsk8wrn4-nixpkgs-review-2.4.2/lib/python3.8/site-packages/nixpkgs_review/cli/pr.py", line 65, in pr_command
    review.start_review(attrs, pr, args.post_result)
  File "/nix/store/9j1c708lhx3qj0l6fxanwjqjgsk8wrn4-nixpkgs-review-2.4.2/lib/python3.8/site-packages/nixpkgs_review/review.py", line 211, in start_review
    nix_shell(report.built_packages(), self.builddir.path)
  File "/nix/store/9j1c708lhx3qj0l6fxanwjqjgsk8wrn4-nixpkgs-review-2.4.2/lib/python3.8/site-packages/nixpkgs_review/nix.py", line 44, in nix_shell
    sh(["nix-shell", str(shell)], cwd=cache_directory)
  File "/nix/store/9j1c708lhx3qj0l6fxanwjqjgsk8wrn4-nixpkgs-review-2.4.2/lib/python3.8/site-packages/nixpkgs_review/utils.py", line 29, in sh
    return subprocess.run(command, cwd=cwd, check=True, text=True)
  File "/nix/store/z65l1jqvxa58zzwwa3bvglb6asj4y8cv-python3-3.8.5/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['nix-shell', '/home/kea/.cache/nixpkgs-review/pr-106645-6/shell.nix']' returned non-zero exit status 1.
```

**Comment by Mic92** [comment]
I am not quite sure if I should ignore errors from `nix-shell` here.

**Comment by abathur** [comment]
I ran into this as well. I was just doing a very basic smoke test so my invocation didn't work:
```
$ results/resholve.resholve/bin/resholve --interpreter blah
usage: resholve [options] script ...
resholve: error: one of the arguments --path --inputs is required

╓─[ nixpkgs ] ~/.cache/nixpkgs-review/rev-4098b2f08a39b510726fd3091370a527ddd1b25d
$ exit
exit
$ git worktree prune
Traceback (most recent call last):
  File "/nix/store/bmwqail6v3ddmn55mnvby448a5wr85qp-nixpkgs-review-2.5.0/bin/.nixpkgs-review-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/bmwqail6v3ddmn55mnvby448a5wr85qp-nixpkgs-review-2.5.0/lib/python3.8/site-packages/nixpkgs_review/__init__.py", line 10, in main
    cli.main(command, args)
  File "/nix/store/bmwqail6v3ddmn55mnvby448a5wr85qp-nixpkgs-review-2.5.0/lib/python3.8/site-packages/nixpkgs_review/cli/__init__.py", line 228, in main
    args.func(args)
  File "/nix/store/bmwqail6v3ddmn55mnvby448a5wr85qp-nixpkgs-review-2.5.0/lib/python3.8/site-packages/nixpkgs_review/cli/rev.py", line 11, in rev_command
    review_local_revision(f"rev-{commit}", args, commit)
  File "/nix/store/bmwqail6v3ddmn55mnvby448a5wr85qp-nixpkgs-review-2.5.0/lib/python3.8/site-packages/nixpkgs_review/review.py", line 414, in review_local_revision
    review.review_commit(args.branch, args.remote, commit, staged)
  File "/nix/store/bmwqail6v3ddmn55mnvby448a5wr85qp-nixpkgs-review-2.5.0/lib/python3.8/site-packages/nixpkgs_review/review.py", line 237, in review_commit
    self.start_review(self.build_commit(branch_rev, reviewed_commit, staged))
  File "/nix/store/bmwqail6v3ddmn55mnvby448a5wr85qp-nixpkgs-review-2.5.0/lib/python3.8/site-packages/nixpkgs_review/review.py", line 227, in start_review
    nix_shell(report.built_packages(), self.builddir.path)
  File "/nix/store/bmwqail6v3ddmn55mnvby448a5wr85qp-nixpkgs-review-2.5.0/lib/python3.8/site-packages/nixpkgs_review/nix.py", line 44, in nix_shell
    sh(["nix-shell", str(shell)], cwd=cache_directory)
  File "/nix/store/bmwqail6v3ddmn55mnvby448a5wr85qp-nixpkgs-review-2.5.0/lib/python3.8/site-packages/nixpkgs_review/utils.py", line 30, in sh
    return subprocess.run(command, cwd=cwd, check=True, text=True)
  File "/nix/store/v3qi2n1cb9bj8h3076p3rz5fg0kpzz53-python3-3.8.6/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['nix-shell', '/Users/abathur/.cache/nixpkgs-review/rev-4098b2f08a39b510726fd3091370a527ddd1b25d/shell.nix']' returned non-zero exit status 2.
```

Not sure if it's appropriate, but I wonder if late-modifying the nix-shell environment with something like below would work for letting the nix-shell invocation itself fail as needed, but swallow this error if the user manually exits after issuing a command that didn't return 0.

```bash
initial_shlvl="$SHLVL"
exit(){
  if [[ "$SHLVL" == "$initial_shlvl" ]]; then
    builtin exit 0
  else
    builtin exit
fi
```

**Comment by Mic92** [comment]
Should be fixed in https://github.com/Mic92/nixpkgs-review/commit/59602f2144afaffeba0385c10cfa469157130b17#diff-f5b281a937846b7bc507e9a95a782fac5b1bcfcec1ea1a2348abc32b0282038eR45
