### ISSUE TITLE
HTTP Error 400: Bad Request

### ISSUE THREAD

**Issue by GabrielDougherty** [Mic92/nixpkgs-review#321]
Hi, I am getting `HTTP Error 400: Bad Request` when I am doing nixpkgs-review. It has worked for the past couple weeks without issue. Also the GitHub API status page does not indicate a service outage: https://www.githubstatus.com/

Here is the error output:

<details>

```
gabriel@pop-os:~/ws/nixpkgs$ nix run nixpkgs#nixpkgs-review pr 218587
$ git worktree prune
Traceback (most recent call last):
  File "/nix/store/0gc4pxnrmxihkfmv4jjmmvqrpmbb42q0-nixpkgs-review-2.8.0/bin/.nixpkgs-review-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/0gc4pxnrmxihkfmv4jjmmvqrpmbb42q0-nixpkgs-review-2.8.0/lib/python3.10/site-packages/nixpkgs_review/__init__.py", line 10, in main
    cli.main(command, args)
  File "/nix/store/0gc4pxnrmxihkfmv4jjmmvqrpmbb42q0-nixpkgs-review-2.8.0/lib/python3.10/site-packages/nixpkgs_review/cli/__init__.py", line 301, in main
    return cast(str, args.func(args))
  File "/nix/store/0gc4pxnrmxihkfmv4jjmmvqrpmbb42q0-nixpkgs-review-2.8.0/lib/python3.10/site-packages/nixpkgs_review/cli/pr.py", line 68, in pr_command
    contexts.append((pr, builddir.path, review.build_pr(pr)))
  File "/nix/store/0gc4pxnrmxihkfmv4jjmmvqrpmbb42q0-nixpkgs-review-2.8.0/lib/python3.10/site-packages/nixpkgs_review/review.py", line 202, in build_pr
    packages_per_system = self.github_client.get_borg_eval_gist(pr)
  File "/nix/store/0gc4pxnrmxihkfmv4jjmmvqrpmbb42q0-nixpkgs-review-2.8.0/lib/python3.10/site-packages/nixpkgs_review/github.py", line 86, in get_borg_eval_gist
    for line in urllib.request.urlopen(raw_gist_url):
  File "/nix/store/0n4y44dnaxafqs7cg625aldrb152x7bx-python3-3.10.10/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/nix/store/0n4y44dnaxafqs7cg625aldrb152x7bx-python3-3.10.10/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/nix/store/0n4y44dnaxafqs7cg625aldrb152x7bx-python3-3.10.10/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/nix/store/0n4y44dnaxafqs7cg625aldrb152x7bx-python3-3.10.10/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/nix/store/0n4y44dnaxafqs7cg625aldrb152x7bx-python3-3.10.10/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/nix/store/0n4y44dnaxafqs7cg625aldrb152x7bx-python3-3.10.10/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request
```

<details>

**Comment by figsoda** [comment]
I can consistently reproduce this, but only on this specific PR :thinking:

**Comment by figsoda** [comment]
nevermind i can reproduce this on more PRs now
