### ISSUE TITLE
subprocess.CalledProcessError: Command '['nix-env', '--extra-experimental-features', 'no-url-literals', '--option', 'system', 'x86_64-linux', '-f', '/home/bbigras/.cache/nixpkgs-review/rev-c283f7a9891027c8809f08a618b97cbf01ab90b7-1/nixpkgs', '-qaP', '--xml', '--out-path', '--show-trace', '--no-allow-import-from-derivation']' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by bbigras** [Mic92/nixpkgs-review#331]
```
❯ nix run github:Mic92/nixpkgs-review rev HEAD
$ git -c fetch.prune=false fetch --no-tags --force https://github.com/NixOS/nixpkgs master:refs/nixpkgs-review/0
$ git worktree add /home/bbigras/.cache/nixpkgs-review/rev-c283f7a9891027c8809f08a618b97cbf01ab90b7-1/nixpkgs b04b3345f16716f7289724286cdc8474d4758a41
Préparation de l'arbre de travail (HEAD détachée b04b3345f16)
Mise à jour des fichiers: 100% (34789/34789), fait.
HEAD est maintenant à b04b3345f16 Merge pull request #195082 from cmm/system76-scheduler
$ nix-env --extra-experimental-features no-url-literals --option system x86_64-linux -f /home/bbigras/.cache/nixpkgs-review/rev-c283f7a9891027c8809f08a618b97cbf01ab90b7-1/nixpkgs -qaP --xml --out-path --show-trace --no-allow-import-from-derivation
        error: interrupted by the user
$ git worktree prune
Traceback (most recent call last):
  File "/nix/store/z662qs4n292mysbcxhzds8979glh1fc1-nixpkgs-review/bin/.nixpkgs-review-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/z662qs4n292mysbcxhzds8979glh1fc1-nixpkgs-review/lib/python3.10/site-packages/nixpkgs_review/__init__.py", line 10, in main
    cli.main(command, args)
  File "/nix/store/z662qs4n292mysbcxhzds8979glh1fc1-nixpkgs-review/lib/python3.10/site-packages/nixpkgs_review/cli/__init__.py", line 304, in main
    return cast(str, args.func(args))
  File "/nix/store/z662qs4n292mysbcxhzds8979glh1fc1-nixpkgs-review/lib/python3.10/site-packages/nixpkgs_review/cli/rev.py", line 14, in rev_command
    return review_local_revision(
  File "/nix/store/z662qs4n292mysbcxhzds8979glh1fc1-nixpkgs-review/lib/python3.10/site-packages/nixpkgs_review/review.py", line 538, in review_local_revision
    review.review_commit(builddir.path, args.branch, commit, staged, print_result)
  File "/nix/store/z662qs4n292mysbcxhzds8979glh1fc1-nixpkgs-review/lib/python3.10/site-packages/nixpkgs_review/review.py", line 291, in review_commit
    self.build_commit(branch_rev, reviewed_commit, staged),
  File "/nix/store/z662qs4n292mysbcxhzds8979glh1fc1-nixpkgs-review/lib/python3.10/site-packages/nixpkgs_review/review.py", line 153, in build_commit
    base_packages = list_packages(
  File "/nix/store/z662qs4n292mysbcxhzds8979glh1fc1-nixpkgs-review/lib/python3.10/site-packages/nixpkgs_review/review.py", line 371, in list_packages
    subprocess.run(cmd, stdout=tmp, check=True)
  File "/nix/store/abax98471z8fshv4b9p46bkh3lxmpy0z-python3-3.10.9/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['nix-env', '--extra-experimental-features', 'no-url-literals', '--option', 'system', 'x86_64-linux', '-f', '/home/bbigras/.cache/nixpkgs-review/rev-c283f7a9891027c8809f08a618b97cbf01ab90b7-1/nixpkgs', '-qaP', '--xml', '--out-path', '--show-trace', '--no-allow-import-from-derivation']' returned non-zero exit status 1.
```

**Comment by figsoda** [comment]
>         error: interrupted by the user

Did you press `ctrl-c` on accident? If not, can you try to reproduce this error?

**Comment by bbigras** [comment]
oh sorry I missed that. I actually ran out of ram.

I'll reopen if I really have this problem.

**Comment by itslychee** [comment]
I've been getting this same issue while trying to review PRs from nixpkgs, I have plenty of RAM so that shouldn't be a limitation of why it keeps hanging on this command. Had to stop the program as it was freezing my system.
