### ISSUE TITLE
Error on list_packages

### ISSUE THREAD

**Issue by cwyc** [Mic92/nixpkgs-review#387]
I find that nixpkgs-review fails with `NixpkgsReviewError: Failed to list packages: nix-env failed with exit code -9`.

To replicate:
- Running nixos 23.11
- Clone nixpkgs master (currently at eef63ea04722d812a09a5974ed18c9761088a6e1) and enter directory
- Run `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`

Log:
```
nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"
this path will be fetched (0.01 MiB download, 0.05 MiB unpacked):
  /nix/store/kv5wkk7xgc8paw9azshzlmxraffqcg0i-stdenv-linux
copying path '/nix/store/kv5wkk7xgc8paw9azshzlmxraffqcg0i-stdenv-linux' from 'https://cache.nixos.org'...
$ git -c fetch.prune=false fetch --no-tags --force https://github.com/NixOS/nixpkgs master:refs/nixpkgs-review/0
remote: Enumerating objects: 69, done.
remote: Counting objects: 100% (47/47), done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 69 (delta 34), reused 38 (delta 32), pack-reused 22
Unpacking objects: 100% (69/69), 423.37 KiB | 1.35 MiB/s, done.
From https://github.com/NixOS/nixpkgs
   8c1a6046a232..55ae7c58f3c0  master     -> refs/nixpkgs-review/0
$ git worktree add /home/cwyc/.cache/nixpkgs-review/rev-eef63ea04722d812a09a5974ed18c9761088a6e1-1/nixpkgs 55ae7c58f3c0522c7afc9fb3d536ba90849e17bf
Preparing worktree (detached HEAD 55ae7c58f3c0)
Updating files: 100% (39288/39288), done.
HEAD is now at 55ae7c58f3c0 Merge pull request #285301 from ibbem/gitTracked-shallow
$ nix-env --extra-experimental-features no-url-literals --option system x86_64-linux -f <nixpkgs> --nix-path nixpkgs=/home/cwyc/.cache/nixpkgs-review/rev-eef63ea04722d812a09a5974ed18c9761088a6e1-1/nixpkgs nixpkgs-overlays=/run/user/1000/tmp3iq3s5fx -qaP --xml --out-path --show-trace --no-allow-import-from-derivation
$ git worktree remove -f /home/cwyc/.cache/nixpkgs-review/rev-eef63ea04722d812a09a5974ed18c9761088a6e1-1/nixpkgs
Traceback (most recent call last):
  File "/nix/store/ayhqdyya71fz1j71n53wljyzbj6b94cn-nixpkgs-review-2.10.3/bin/.nixpkgs-review-wrapped", line 9, in <module>
    sys.exit(main())
             ^^^^^^
  File "/nix/store/ayhqdyya71fz1j71n53wljyzbj6b94cn-nixpkgs-review-2.10.3/lib/python3.11/site-packages/nixpkgs_review/__init__.py", line 10, in main
    cli.main(command, args)
  File "/nix/store/ayhqdyya71fz1j71n53wljyzbj6b94cn-nixpkgs-review-2.10.3/lib/python3.11/site-packages/nixpkgs_review/cli/__init__.py", line 334, in main
    return cast(str, args.func(args))
                     ^^^^^^^^^^^^^^^
  File "/nix/store/ayhqdyya71fz1j71n53wljyzbj6b94cn-nixpkgs-review-2.10.3/lib/python3.11/site-packages/nixpkgs_review/cli/rev.py", line 14, in rev_command
    return review_local_revision(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/ayhqdyya71fz1j71n53wljyzbj6b94cn-nixpkgs-review-2.10.3/lib/python3.11/site-packages/nixpkgs_review/review.py", line 582, in review_local_revision
    review.review_commit(builddir.path, args.branch, commit, staged, print_result)
  File "/nix/store/ayhqdyya71fz1j71n53wljyzbj6b94cn-nixpkgs-review-2.10.3/lib/python3.11/site-packages/nixpkgs_review/review.py", line 310, in review_commit
    self.build_commit(branch_rev, reviewed_commit, staged),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/ayhqdyya71fz1j71n53wljyzbj6b94cn-nixpkgs-review-2.10.3/lib/python3.11/site-packages/nixpkgs_review/review.py", line 161, in build_commit
    base_packages = list_packages(
                    ^^^^^^^^^^^^^^
  File "/nix/store/ayhqdyya71fz1j71n53wljyzbj6b94cn-nixpkgs-review-2.10.3/lib/python3.11/site-packages/nixpkgs_review/review.py", line 398, in list_packages
    raise NixpkgsReviewError(
nixpkgs_review.errors.NixpkgsReviewError: Failed to list packages: nix-env failed with exit code -9
```

**Comment by Mic92** [comment]
This error usually appears if nix-env went out-of-memory. There is little I can do to fix it. If you wait for ofborg to evaluate nixpkgs, you can use the cached version to not have to evaluate locally.
