### ISSUE TITLE
fatal: '/home/bart/.cache/nixpkgs-review/pr-369048-1/nixpkgs' is not a working tr

### ISSUE THREAD

**Issue by magnetophon** [Mic92/nixpkgs-review#445]
My nixpkgs-review is in a broken state somehow.
Whenever I try to review a PR, I get:

```
-> Attempting to fetch eval results from GitHub actions
$ git worktree remove -f /home/bart/.cache/nixpkgs-review/pr-369048-1/nixpkgs
fatal: '/home/bart/.cache/nixpkgs-review/pr-369048-1/nixpkgs' is not a working tree
Failed to remove worktree at /home/bart/.cache/nixpkgs-review/pr-369048-1/nixpkgs. Please remove it manually. Git failed with: 128
Traceback (most recent call last):
  File "/nix/store/lzz1i98h78miinzx3yg6ly7kl4ypxd42-nixpkgs-review-3.0.0/bin/.nixpkgs-review-wrapped", line 9, in <module>
    sys.exit(main())
             ^^^^^^
  File "/nix/store/lzz1i98h78miinzx3yg6ly7kl4ypxd42-nixpkgs-review-3.0.0/lib/python3.12/site-packages/nixpkgs_review/__init__.py", line 10, in main
    cli.main(command, args)
  File "/nix/store/lzz1i98h78miinzx3yg6ly7kl4ypxd42-nixpkgs-review-3.0.0/lib/python3.12/site-packages/nixpkgs_review/cli/__init__.py", line 348, in main
    return cast(str, args.func(args))
                     ^^^^^^^^^^^^^^^
  File "/nix/store/lzz1i98h78miinzx3yg6ly7kl4ypxd42-nixpkgs-review-3.0.0/lib/python3.12/site-packages/nixpkgs_review/cli/pr.py", line 97, in pr_command
    contexts.append((pr, builddir.path, review.build_pr(pr)))
                                        ^^^^^^^^^^^^^^^^^^^
  File "/nix/store/lzz1i98h78miinzx3yg6ly7kl4ypxd42-nixpkgs-review-3.0.0/lib/python3.12/site-packages/nixpkgs_review/review.py", line 300, in build_pr
    packages_per_system = self.github_client.get_github_action_eval_result(pr)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/lzz1i98h78miinzx3yg6ly7kl4ypxd42-nixpkgs-review-3.0.0/lib/python3.12/site-packages/nixpkgs_review/github.py", line 182, in get_github_action_eval_result
    changed_paths: Any = self.get_json_from_artifact(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/lzz1i98h78miinzx3yg6ly7kl4ypxd42-nixpkgs-review-3.0.0/lib/python3.12/site-packages/nixpkgs_review/github.py", line 119, in get_json_from_artifact
    with no_redirect_opener.open(req) as resp:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/zv1kaq7f1q20x62kbjv6pfjygw5jmwl6-python3-3.12.7/lib/python3.12/urllib/request.py", line 521, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/nix/store/zv1kaq7f1q20x62kbjv6pfjygw5jmwl6-python3-3.12.7/lib/python3.12/urllib/request.py", line 630, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/nix/store/zv1kaq7f1q20x62kbjv6pfjygw5jmwl6-python3-3.12.7/lib/python3.12/urllib/request.py", line 559, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/zv1kaq7f1q20x62kbjv6pfjygw5jmwl6-python3-3.12.7/lib/python3.12/urllib/request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/nix/store/zv1kaq7f1q20x62kbjv6pfjygw5jmwl6-python3-3.12.7/lib/python3.12/urllib/request.py", line 639, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

I tried ``rm -rf /home/bart/.cache/nixpkgs-review``, but that doesn't help.
On each subsequent run the number of the worktree it tries to remove increases:

```
-> Attempting to fetch eval results from GitHub actions
$ git worktree remove -f /home/bart/.cache/nixpkgs-review/pr-369048-2/nixpkgs
fatal: '/home/bart/.cache/nixpkgs-review/pr-369048-2/nixpkgs' is not a working tree
```

**Comment by ethancedwards8** [comment]
I'm getting this too.

**Comment by ethancedwards8** [comment]
I'm now getting this on my MacOS system too

**Comment by Mic92** [comment]
The issue is the 403 api error. Try nixpkgs-review 3.0.1 where we improved the handling of Github tokesn. I would recommend installing `gh` and run `gh auth login` to use the evaluation results on github.

**Comment by magnetophon** [comment]
Thank you!
 nixpkgs-review 3.0.1 fixes it for me.
